[package]
name = "koharu-app"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
alphanumeric-sort = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hayro = { workspace = true }
image = { workspace = true }
koharu-agent = { workspace = true }
koharu-desktop = { workspace = true }
koharu-ml = { workspace = true }
koharu-metrics = { workspace = true }
koharu-pipeline = { workspace = true }
koharu-psd = { workspace = true }
koharu-renderer = { workspace = true }
koharu-rasterizer = { workspace = true, features = ["native"] }
koharu-runtime = { workspace = true }
koharu-scene = { workspace = true }
koharu-secrets = { workspace = true }
koharu-translator = { workspace = true }
open = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
rars = { workspace = true }
rfd = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
specta-typescript = { workspace = true }
strum = { workspace = true }
tauri = { workspace = true }
tauri-plugin-log = { workspace = true }
tauri-plugin-opener = { workspace = true }
tauri-plugin-process = { workspace = true }
tauri-plugin-single-instance = { workspace = true }
tauri-plugin-updater = { workspace = true }
tauri-plugin-window-state = { workspace = true }
tauri-specta = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }
webp = { workspace = true }
zip = { workspace = true }
